import ApolloClientProvider from "@/apollo/apolloClientProvider";
import ThemeRegistry from "@/theme/themeRegistry";
import "./globals.css";
import type { Metadata } from "next";
import NextAuthSessionProvider from "./api/auth/[...nextauth]/providers/sessionProvider";
import NextThemeProvider from "@/theme/nextThemeProvider";
import AppHeaderServerSiderComponent from "@/containers/appHeaderServerSide/appHeaderServerSide";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NextAuthSessionProvider>
          <NextThemeProvider>
            <ApolloClientProvider>
              <ThemeRegistry>
                <AppHeaderServerSiderComponent />
                <main>{children}</main>
              </ThemeRegistry>
            </ApolloClientProvider>
          </NextThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
