import ApolloClientProvider from "@/apollo/apolloClientProvider";
import ThemeRegistry from "@/theme/themeRegistry";
//import "./globals.css";
import type { Metadata } from "next";
import NextAuthSessionProvider from "./api/auth/[...nextauth]/providers/sessionProvider";
import NextThemeProvider from "@/theme/nextThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          <NextThemeProvider>
            <ApolloClientProvider>
              <ThemeRegistry>{children}</ThemeRegistry>
            </ApolloClientProvider>
          </NextThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
